name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8
    
    - name: Check code formatting with Black
      run: black --check src/
    
    - name: Check import sorting with isort
      run: isort --check-only src/
    
    - name: Lint with flake8
      run: flake8 src/ --max-line-length=100 --extend-ignore=E203,W503

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest pytest-cov
    
    - name: Download test data
      run: python -m data.data_loader
    
    - name: Run tests with coverage
      run: |
        pytest tests/ --cov=src --cov-report=xml --cov-report=html
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml

  build-docker:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: [lint-and-format, test]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build API image
      run: docker build -t churn-api:latest -f docker/Dockerfile.api .
    
    - name: Build Dashboard image
      run: docker build -t churn-dashboard:latest -f docker/Dockerfile.dashboard .
    
    - name: Test Docker containers
      run: |
        docker-compose -f docker/docker-compose.yml up -d
        sleep 30
        curl http://localhost:8000/health
        docker-compose -f docker/docker-compose.yml down